[package]
name = "blog-server"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
brotli = "8.0.0"
dashmap = "6.1.0"
flate2 = "1.1.1"
twox-hash = "2.1.0"
walkdir = "2.5.0"

[dependencies.tokio]
version = "1.44.2"
# TODO: slim down features
features = ["full"]

[dependencies.tower]
version = "0.5.2"
features = ["load-shed", "timeout"]

[profile.deploy]
inherits = "release"
lto = true
codegen-units = 1
